### ISSUE TITLE
NowcastingGPT Model Code Availability

### ISSUE THREAD

**Issue by bugsuse** [Cmeo97/NowcastingGPT#1]
Is there any plans to release the model code?

**Comment by Cmeo97** [comment]
The code will be released in a few weeks! Probably right after NeurIPs submission deadline, we are extremely busy right now. Thanks for understanding. 

Bests,
Cristian

**Comment by GreenRefraction** [comment]
Any updates on this? NeurIPs deadline was May 22nd, which was a while ago

**Comment by Cmeo97** [comment]
Sorry for the delay, we are working on it. We took some day off after NeurIps, we also had a submission for a ICML workshop, so we didn’t have a lot of time and we would like to share the code as clean as possible. The code will be realized as soon as possible. Thank you for patience!

**Comment by Cmeo97** [comment]
Hi! The code is finally available, apologies for being so late.
